name: Publish NateIQ Core to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'bun.lockb'
      - 'src/**'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    name: Build & Publish with Bun
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@get-nate:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish to GitHub Packages
        run: bun publish --access restricted