on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Configure registry auth
        run: |
          echo "@get-nate:registry=https://npm.pkg.github.com" >> ~/.bunfig.toml
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PUBLISH_TOKEN }}" >> ~/.bunfig.toml

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish
        run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}